#==============================
#テーマの設定
#==============================
[theme]
#チェックボックスをチェックしたときやスライダーの点の色
primaryColor = "#008080"
#メインの背景
backgroundColor = "#F5F5F5"
#インプットボックスやサイドバーなどの背景
secondaryBackgroundColor = "#E0E0E0"
#テキストの色
textColor = "#000000"
#フォント
font = "serif"